### ISSUE TITLE
conseil-administration

### ISSUE THREAD

**Issue by davebulaval** [dot-layer/charte-osbl#1]
Il manque le poste de moi et jc.

**Comment by davebulaval** [comment]
C'était VP comm et moi vp développement ?

**Comment by jtbai** [comment]
J'ai mis les job "minimales". dans le fond pas qu'on aime pas vos poste, mais jpense meme que j'Aurais pas du mettre trésorier.
techniquement tu peux "déléguer" ces pouvoirs la a un membre ou un commité. Mais président et secrétaire tu peux pas faire ca à moins que tu aille qqn dans le CA
